import { Award, BarChart3, Flame, Heart, RefreshCw, Sparkles } from 'lucide-react';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import client from '../../api/client.js';
import GlassCard from '../../components/GlassCard.jsx';
import PageHeader from '../../components/PageHeader.jsx';

export default function Analytics() {
  const [data, setData] = useState(null); const [achievements, setAchievements] = useState([]); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [analytics, badges, smart] = await Promise.all([client.get('/analytics?days=90'), client.get('/achievements'), client.get('/smart-memories?limit=1')]); setData(analytics.data); setAchievements(badges.data.achievements || []); setSummary(smart.data.items?.[0] || null); } catch (error) { toast.error(error.response?.data?.message || 'Analytics could not load.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const counts = data?.counts || {};
  return <><PageHeader eyebrow="Your love, in little patterns" title="Relationship analytics" subtitle="A gentle look at the memories you are building together." action={<button className="soft-button" onClick={load}><RefreshCw size={15} /> Refresh</button>} />{loading ? <div className="loading-grid"><div className="glass-card skeleton-card" /><div className="glass-card skeleton-card" /><div className="glass-card skeleton-card" /></div> : <><div className="analytics-stat-grid">{[['Memories', counts.memories, Heart], ['Letters', counts.letters, Sparkles], ['Songs', counts.songs, BarChart3], ['Streak', `${data?.streaks?.current || 0} days`, Flame]].map(([label, value, Icon]) => <GlassCard className="analytics-stat" key={label}><Icon size={18} /><strong>{value || 0}</strong><span>{label}</span></GlassCard>)}</div><div className="analytics-layout"><GlassCard className="analytics-panel"><div className="card-heading"><div><span className="eyebrow">Mood rhythm</span><h2>How your days feel</h2></div><span className="date-chip">90 days</span></div>{data?.moodTrend?.length ? <div className="mood-trend-list">{data.moodTrend.map((mood) => <div key={mood._id} className="trend-row"><span>{mood._id || 'Unlisted'}</span><i><b style={{ width: `${Math.min(100, mood.count * 12)}%` }} /></i><strong>{mood.count}</strong></div>)}</div> : <div className="empty-state compact-empty"><h3>No mood rhythm yet</h3><p>Daily moods will turn into a sweet little pattern here.</p></div>}</GlassCard><GlassCard className="analytics-panel"><div className="card-heading"><div><span className="eyebrow">Smart memory</span><h2>Recent recap</h2></div><Sparkles size={20} /></div>{summary ? <><h3>{summary.title}</h3><p className="analytics-copy">{summary.summary}</p></> : <div className="empty-state compact-empty"><h3>Ready when you are</h3><p>Generate a recap after adding a few memories.</p></div>}</GlassCard></div><GlassCard className="analytics-panel achievements-panel"><div className="card-heading"><div><span className="eyebrow">Little milestones</span><h2>Achievements</h2></div><Award size={20} /></div><div className="achievement-grid">{achievements.map((item) => <div className={`achievement ${item.unlocked ? 'unlocked' : ''}`} key={item.key}><span>{item.unlocked ? '🏆' : '✦'}</span><div><strong>{item.title}</strong><small>{item.progress}/{item.target} · {item.description}</small></div></div>)}</div></GlassCard></>}</>;
}
